FROM python:3.9-slim

WORKDIR ./Zamburinhas/microservicio_red_neuronal

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install flask-cors

COPY . .

CMD ["python3", "microservice.py"]
